"""The perfect-fit function: interpolators over draw spacetime.

The most natural formulation of lottery prediction there is: the draw history is
a set of points along the time axis, so there must exist a function through all
of them, and evaluating it one step past the end is the next draw. The premise
is even *true* — such functions exist, infinitely many of them, and three are
constructed exactly here.

That is also where it ends, and the interesting part is that the failure is
quantitative rather than philosophical. Fitting the past perfectly costs
nothing: interpolation is always possible and carries no information. The work
is all in *selecting which* perfect fit continues into the future, and selection
is paid for in bits — log2 C(37,6)*7 = 23.96 bits per future draw. The
`incompressibility` test in `bench.randomness` measures how many such bits the
archive contains beyond its own entropy: none that two general-purpose
compressors can find, while a control sequence actually generated by a simple
function compresses to ~10% of the floor. The three families below make the
same point constructively: each fits every past draw to machine precision, and
they disagree with each other about the next one. The data has no opinion on
which is right, because under a fair draw the continuation is independent of
the past.

These predictors are shipped as labelled controls, like `MemorisingDateLookup`:
their in-sample reconstruction is perfect by construction, their walk-forward
score is chance, and the gap between those two numbers is the product.
"""

from __future__ import annotations

import logging

import numpy as np

from .data import N_DRAWN, N_NUMBERS, N_STRONG, Draws
from .predictors import Predictor

logger = logging.getLogger(__name__)

_UNIFORM_STRONG = 1.0 / N_STRONG


class PerfectFitDFT(Predictor):
    """Trigonometric interpolation — the unique minimal-bandwidth perfect fit.

    The discrete Fourier basis is the canonical answer to "one smooth function
    through all n points". It reconstructs every past draw to ~1e-7. And because
    every basis function has period n, the extrapolation f(n) equals f(0)
    *identically*: the unique minimal-bandwidth function through fourteen years
    of draws predicts, as the next draw, the draw of 2012-01-03.

    That is not a bug in the Fourier transform. It is what "the data does not
    constrain the continuation" looks like once a basis makes it concrete.
    """

    name = "Perfect-fit function (DFT)"
    description = (
        "Trigonometric interpolation through every past draw — the unique minimal-bandwidth "
        "function fitting the whole history exactly. Its one-step extrapolation is f(0): it "
        "predicts the first draw in the archive. Included as a control."
    )

    def scores(self, history: Draws) -> tuple[np.ndarray, np.ndarray]:
        # f(n) = f(0) by periodicity; asserted, not assumed, in the tests.
        return history.multi_hot[0].astype(np.float64), np.full(N_STRONG, _UNIFORM_STRONG)

    def reconstruct(self, history: Draws) -> np.ndarray:
        """Evaluate the fitted function at every past index. Exact by definition."""
        coef = np.fft.rfft(history.multi_hot, axis=0)
        return np.fft.irfft(coef, n=len(history), axis=0)


class PerfectFitSpline(Predictor):
    """A natural cubic spline through every past draw, extrapolated one step.

    Also an exact fit — zero error at every knot. Its extrapolation follows the
    final cubic segment, which promptly leaves [0, 1]: on the real archive the
    "probability" of some numbers comes out below -7 and above +10. A function
    can match every observed frequency perfectly and still know nothing about
    what a probability is.
    """

    name = "Perfect-fit function (spline)"
    description = (
        "Natural cubic spline through every past draw, evaluated one step past the end. "
        "Fits the history exactly; extrapolates values far outside [0, 1]. A control."
    )

    def scores(self, history: Draws) -> tuple[np.ndarray, np.ndarray]:
        from scipy.interpolate import CubicSpline

        n = len(history)
        t = np.arange(n, dtype=np.float64)
        vals = np.array(
            [CubicSpline(t, history.multi_hot[:, j])(float(n)) for j in range(N_NUMBERS)]
        )
        return vals, np.full(N_STRONG, _UNIFORM_STRONG)


class PerfectFitPolynomial(Predictor):
    """Degree-5 polynomial through the last six draws, extrapolated one step.

    The local version of the same idea, for people who feel the full history is
    "too old to matter". Exact on its window (residuals ~1e-13); the
    extrapolated values span roughly [-16, +32], because a degree-5 polynomial
    leaving its data does what polynomials do.
    """

    name = "Perfect-fit function (polynomial)"
    description = (
        "Degree-5 polynomial through the last six draws per number, evaluated one step "
        "ahead. Exact on its window; wildly divergent beyond it. A control."
    )

    window = N_DRAWN  # 6 points -> degree 5, exact

    def scores(self, history: Draws) -> tuple[np.ndarray, np.ndarray]:
        w = self.window
        tw = np.arange(w, dtype=np.float64)
        recent = history.multi_hot[-w:]
        vals = np.array(
            [np.polyval(np.polyfit(tw, recent[:, j], w - 1), float(w)) for j in range(N_NUMBERS)]
        )
        return vals, np.full(N_STRONG, _UNIFORM_STRONG)


def spacetime_suite() -> list[Predictor]:
    """The three perfect-fit controls, in report order."""
    return [PerfectFitDFT(), PerfectFitSpline(), PerfectFitPolynomial()]
